services:
  app:
    image: tvwatchlist-app:local
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.dev
    container_name: watchlist-app
    restart: unless-stopped
    environment:
      OPCACHE_VALIDATE_TIMESTAMPS: 0
      ENV: dev
      XDEBUG_MODE: "off"
    volumes:
      - ./app:/var/www/html:rw,cached
    networks:
      - app-network
    expose:
      - "9000"
    # Ensure php-fpm is the command
    command: ["php-fpm", "-F", "-R"]

  nginx:
    container_name: tvwatchlist-nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./app/public:/var/www/html/public
      - ./docker/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  database:
    container_name: database
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: api
      MONGO_INITDB_ROOT_USERNAME: api
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db_data:/data/db:rw
      - ./backups:/backups:rw
    networks:
      - app-network
    ports:
      - "27017:27017"
    command: ["mongod", "--auth", "--bind_ip_all"]

volumes:
  db_data: {}

networks:
  app-network:
    driver: bridge